previewsEnabled: true
services:
- type: web
  autoDeploy: true
  initialDeployHook: ./bin/dephook.sh
  name: tcp-echo
  env: docker
  branch: main
  healthCheckPath: /health
  envVars:
    - key: PORT
      value: 80