apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-echo
spec:
  template:
    spec:
      containers:
        - name: tcp-echo
          image: ghcr.io/elauffenburger/tcp_echo@sha256:ed8f3174ec1a2b7d5567403e59a510525dfce670b79669e0c1600848f1d65695